title: Impact Evaluation Framework
description: Framework técnico aberto e reutilizável para avaliação de resultados e impacto
markdown: kramdown
baseurl: "/impact-evaluation-framework"
url: "https://sayjinblackbelt.github.io"

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
